baseURL = 'https://stepanstoliarzh.github.io/practice-2025-Stoliarzh-Panin-Boykov/'
languageCode = 'en-us'
title = 'Водный спорт (I курс)'
theme = 'blowfish'
defaultContentLanguage = 'ru'
enableRobotsTXT = true

[menu]

  [[menu.main]]
    name = "О проекте"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Участники"
    url = "/participants/"
    weight = 2

  [[menu.main]]
    name = "Журнал"
    url = "/journal/"
    weight = 3

  [[menu.main]]
    name = "Ресурсы"
    url = "/resources/"
    weight = 4

  [[menu.main]]
    name = "Мероприятие"
    url = "/visit/"
    weight = 5

  [[menu.main]]
    name = "Вариативное задание"
    url = "/variant"
    weight = 6
    identifier = "variant"


