baseURL = "https://stepanstoliarzh.github.io/practice-2025-Stoliarzh-Panin-Boykov/"
canonifyURLs = true
languageCode = 'ru'
title = 'Группа проектов тестирования'
theme = 'ananke'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "О проекте"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "team"
    name = "Участники"
    url = "/team/"
    weight = 2

  [[menu.main]]
    identifier = "journal"
    name = "Журнал"
    url = "/journal/"
    weight = 3

  [[menu.main]]
    identifier = "resources"
    name = "Ресурсы"
    url = "/resources/"
    weight = 4

  [[menu.main]]
    name = "Мероприятие"
    url = "/visit/"
    weight = 5

  [[menu.main]]
    name = "Вариативное задание"
    url = "/variant/"
    weight = 6
    
