baseURL = 'https://stepanstoliarzh.github.io/practice-2025-Stoliarzh-Panin-Boykov/'
languageCode = 'ru'
title = 'Водный спорт (I курс)'
theme = 'blowfish'
publishDir = 'docs'

[menu]

  [[menu.main]]
  name = "О проекте"
  url = "/about"
  weight = 1

  [[menu.main]]
  name = "Участники"
  url = "/participants"
  weight = 2

  [[menu.main]]
  name = "Журнал"
  url = "/journal"
  weight = 3

  [[menu.main]]
  name = "Ресурсы"
  url = "/resources"
  weight = 4

  [[menu.main]]
    name = "Вариативное задания"
    pageRef = "/variant"
    weight = 5

[params.assets]
customCSS = ["css/custom.css"]

[params.article]
showDate = false
showReadingTime = false
showWordCount = false

[permalinks]
journal = "/journal/:filename.html"




