baseURL = 'https://example.com/'
languageCode = 'ru-ru'
title = 'GoSpot — Платформа для водного спорта'
theme = "blowfish"

[params]
  assets = ["css/custom.css"]
  
[blowfish]
  colorScheme = "auto"
  logo = "/images/logo.svg"
  logoLink = "/"  # Логотип будет ссылкой на главную
  favicon = "/favicon.ico"

[menu]
  # Главное меню (без пункта "Главная")
  [[menu.main]]
    name = "О проекте"
    url = "/about/"
    weight = 1
    
  [[menu.main]]
    name = "Участники"
    url = "/team/"
    weight = 2
    
  [[menu.main]]
    name = "Журнал"
    url = "/journal/"
    weight = 3
    
  [[menu.main]]
    name = "Ресурсы"
    url = "/resources/"
    weight = 4